# Generated by Django 4.2.3 on 2023-07-25 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('amount_of_money', models.IntegerField(default=1000)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_character', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=1024)),
                ('date_of_birth', models.CharField(max_length=255)),
                ('patronus', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=770)),
                ('xp_points', models.IntegerField(default=10)),
                ('current_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentOwnertoUser', to='cards.user')),
                ('previous_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previousOwnerToUser', to='cards.user')),
            ],
        ),
    ]
