# Generated by Django 4.2.3 on 2023-07-25 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_id_alter_card_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='current_owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentOwnertoUser', to='cards.user'),
        ),
        migrations.AlterField(
            model_name='card',
            name='previous_owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previousOwnerToUser', to='cards.user'),
        ),
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.IntegerField(default=1136),
        ),
        migrations.AlterField(
            model_name='card',
            name='xp_points',
            field=models.IntegerField(default=1),
        ),
    ]
